### ISSUE TITLE
Add clearfix

### ISSUE THREAD

**Issue by zoerooney** [zoerooney/Emi#2]
Replace all instances of overflow:hidden with micro group/ clearfix:

``` css
.group:after {
  content: "";
  display: table;
  clear: both;
}
```
